# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-18.04

steps:
- script: sudo apt-get update -y
  displayName: 'Actualizar Repositorio'

- script: sudo apt-get install default-jre -y
  displayName: 'Instalar Java'

- script: sudo apt-get install openssh-server -y
  displayName: 'Instalar openssh'

#- script: sbt test
#  displayName: 'Correr Pruebas Unitarias'

- task: DownloadSecureFile@1
  name: AppServerKey
  displayName: "Descargar Llave Privada de Servidor de Aplicaciones"
  inputs:
   secureFile: "webserver-01_key.ppk"

- script: sbt rpm:packageBin
  displayName: 'Empaquetar Aplicacion'

   
#- script: echo $(AppServerKey.secureFilePath)

- script: sudo chmod 600 $(AppServerKey.secureFilePath) && sudo scp -v -o StrictHostKeyChecking=no -i $(AppServerKey.secureFilePath) /home/vsts/work/1/s/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm azureuser@23.96.48.228:/home/azureuser/
  displayName: 'Importar RPM a VM Azure'